### ISSUE TITLE
Отзыв на статью «5 хитростей при создании отзывчивого сайта»

### ISSUE THREAD

**Issue by LordotU** [iamstarkov/vstarkov.ru#19]
Спасибо за заметку!

У меня так и не получилось в genymotion последних версий поставить Chrome. :-(

**Comment by iamstarkov** [comment]
@LordotU  даже способ с расшаренными папками не помогает? http://stackoverflow.com/a/20271517/1057730

**Comment by LordotU** [comment]
Точнее, установить получилось, но все безбожно глючило и работать было невозможно. Я вот даже на СО писал, но фитбека нема: http://stackoverflow.com/questions/21308107/how-to-install-chrome-browser-on-android-in-genymotion

**Comment by hudochenkov** [comment]
> Чтобы текст не прыгал в мобильном Вебките, и масштабировался в обычном: "`-webkit-text-size-adjust: 100%;`". 100%, а не none.
> — https://twitter.com/artpolikarpov/status/150276055234650117

**Comment by iamstarkov** [comment]
@hudochenkov поправил

**Comment by merkuriy** [comment]
> ни один эмулятор не сможет в точности повторить все особенности устройств

Мне кажется в данном контексте рассматривается только эмуляция программного обеспечения (операционной системы и т. д.), а не аппаратного (устройства). Поэтому высказывание отчасти не верное. Мы ведь не эмулируем устройства, поэтому девайс в любом случае нужен. А задача эмуляторов для веб разработчиков сводится лишь к обеспечению быстрой и удобной предварительной проверки в разных программных окружениях, не отходя от написания кода и не отпуская клавиатуру/мышь.

**Comment by iamstarkov** [comment]
>  сводится лишь к обеспечению быстрой и удобной предварительной проверки

вся суть в этих словах, так как эмуляторы не могут гарантировать 100% результат, что кажется не противоречит тому, что написано в статье
